[package]
name = "keccak-hasher"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Keccak-256 implementation of the Hasher trait"
license = "GPL-3.0"

[dependencies]
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
tiny-keccak = "1.4.2"
plain_hasher = "0.2"
