[package]
name = "ed25519"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ring = "0.12"
untrusted = "0.5"
substrate-primitives = { version = "0.1", path = "../primitives" }
hex-literal = "0.1"
