[package]
name = "polkadot-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
crunchy = "0.1"
fixed-hash = { git = "https://github.com/rphmeier/primitives.git", branch = "uint-asm-with-feature" }
rustc-hex = { git = "https://github.com/rphmeier/rustc-hex.git", version = "2.0", default_features = false }
serde = { version = "1.0", default_features = false }
serde_derive = "1.0"
uint = { git = "https://github.com/rphmeier/primitives.git", branch = "uint-asm-with-feature" }
ring = "0.12"
untrusted = "0.5"
twox-hash = "1.1.0"
byteorder = "1.1"
blake2-rfc = "0.2.18"
polkadot-runtime-codec = { path = "../runtime-codec", version = "0.1" }

[dev-dependencies]
polkadot-serializer = { path = "../serializer", version = "0.1" }
pretty_assertions = "0.4"

[features]
default = ["std"]
std = ["uint/std", "fixed-hash/std", "polkadot-runtime-codec/std", "serde/std", "rustc-hex/std"]
