[package]
name = "demo-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
log = { version = "0.3", optional = true }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
substrate-codec = { path = "../../substrate/codec" }
substrate-runtime-std = { path = "../../substrate/runtime-std" }
substrate-runtime-io = { path = "../../substrate/runtime-io" }
substrate-runtime-support = { path = "../../substrate/runtime-support" }
substrate-primitives = { path = "../../substrate/primitives" }
substrate-keyring = { path = "../../substrate/keyring" }
demo-primitives = { path = "../primitives" }
integer-sqrt = "0.1.0"

[features]
default = ["std"]
std = [
	"substrate-codec/std",
	"substrate-runtime-std/std",
	"substrate-runtime-io/std",
	"substrate-runtime-support/std",
	"substrate-primitives/std",
	"demo-primitives/std",
	"serde_derive",
	"serde/std",
	"log"
]
