[package]
name = "substrate-runtime-support"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ed25519 = { path = "../ed25519", optional = true }
hex-literal = { version = "0.1.0", optional = true }
substrate-runtime-std = { path = "../runtime-std", default_features = false }
substrate-runtime-io = { path = "../runtime-io", default_features = false }
environmental = { path = "../environmental", optional = true }
substrate-primitives = { path = "../primitives", default_features = false }
substrate-codec = { path = "../codec", default_features = false }

[features]
default = ["std"]
std = [
	"ed25519",
	"hex-literal",
	"environmental",
	"substrate-primitives/std",
	"substrate-runtime-io/std",
	"substrate-codec/std",
	"substrate-runtime-std/std",
]
nightly = []
strict = []
