sudo: false
language: rust
branches:
  only:
  - master

cache: cargo

matrix:
  fast_finish: false
  include:
    - rust: stable

script:
  - cargo test --all
  - cargo clean
  - ./init.sh
  - ./build.sh
  - if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      ./publish-wasm.sh;
    fi
