[[bin]]
name = "polkadot"
path = "polkadot/src/main.rs"

[package]
name = "polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
polkadot-cli = { path = "polkadot/cli" }
ctrlc = { git = "https://github.com/paritytech/rust-ctrlc.git" }

[workspace]
members = [
	"polkadot/api",
	"polkadot/cli",
	"polkadot/collator",
	"polkadot/consensus",
	"polkadot/executor",
	"polkadot/keystore",
	"polkadot/primitives",
	"polkadot/runtime",
	"polkadot/statement-table",
	"polkadot/transaction-pool",
	"polkadot/validator",
	"polkadot/service",
	"substrate/bft",
	"substrate/client",
	"substrate/codec",
	"substrate/environmental",
	"substrate/executor",
	"substrate/keyring",
	"substrate/network",
	"substrate/misbehavior-check",
	"substrate/primitives",
	"substrate/rpc-servers",
	"substrate/rpc",
	"substrate/runtime-io",
	"substrate/runtime-std",
	"substrate/runtime-support",
	"substrate/runtime/consensus",
	"substrate/runtime/council",
	"substrate/runtime/democracy",
	"substrate/runtime/executive",
	"substrate/runtime/primitives",
	"substrate/runtime/session",
	"substrate/runtime/staking",
	"substrate/runtime/system",
	"substrate/runtime/timestamp",
	"substrate/serializer",
	"substrate/state-machine",
	"substrate/test-runtime",
	"demo/runtime",
	"demo/primitives",
	"demo/executor",
	"demo/cli",
	"safe-mix",
]
exclude = [
	"polkadot/runtime/wasm",
	"demo/runtime/wasm",
	"substrate/executor/wasm",
	"substrate/pwasm-alloc",
	"substrate/pwasm-libc",
	"substrate/test-runtime/wasm",
]
