[package]
name = "polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
polkadot-cli = { path = "cli", version = "0.1" }

[workspace]
members = [
	"client",
	"contracts",
	"primitives",
	"rpc",
	"rpc_servers",
	"serializer",
	"state_machine",
	"validator",
]
