[package]
name = "polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
polkadot-cli = { path = "polkadot-cli", version = "0.1" }
polkadot-network = { path = "network" }

[workspace]
members = [
	"client",
	"codec",
	"environmental",
	"executor",
	"network",
	"polkadot-candidate-agreement",
	"polkadot-cli",
	"polkadot-collator",
	"polkadot-executor",
	"polkadot-runtime",
	"polkadot-primitives",
	"polkadot-validator",
	"primitives",
	"rpc",
	"rpc-servers",
	"runtime-io",
	"runtime-std",
	"serializer",
	"state-machine",
]
exclude = [
	"executor/wasm",
	"polkadot-runtime/wasm",
	"pwasm-alloc",
	"pwasm-libc",
]
