[[bin]]
name = "polkadot"
path = "polkadot/src/main.rs"

[package]
name = "polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
polkadot-cli = { path = "polkadot/cli" }

[workspace]
members = [
	"polkadot/api",
	"polkadot/cli",
	"polkadot/collator",
	"polkadot/consensus",
	"polkadot/executor",
	"polkadot/primitives",
	"polkadot/runtime",
	"polkadot/statement-table",
	"polkadot/validator",
	"substrate/bft",
	"substrate/client",
	"substrate/codec",
	"substrate/environmental",
	"substrate/executor",
	"substrate/keyring",
	"substrate/network",
	"substrate/primitives",
	"substrate/rpc-servers",
	"substrate/rpc",
	"substrate/runtime-io",
	"substrate/runtime-std",
	"substrate/runtime-support",
	"substrate/serializer",
	"substrate/state-machine",
	"substrate/test-runtime",
]
exclude = [
	"polkadot/runtime/wasm",
	"substrate/executor/wasm",
	"substrate/pwasm-alloc",
	"substrate/pwasm-libc",
	"substrate/test-runtime/wasm",
]
