[package]
name = "polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
polkadot-cli = { path = "cli", version = "0.1" }

[workspace]
members = [
	"candidate-agreement",
	"client",
	"collator",
	"environmental",
	"executor",
	"primitives",
	"rpc",
	"rpc_servers",
	"native-runtime",
	"runtime-codec",
	"serializer",
	"state_machine",
	"validator",
]
exclude = [
	"wasm-runtime"
]
