[package]
name = "frontier"
version = "0.1.0"
authors = ["Parity Team <admin@parity.io>"]
build = "build.rs"

[dependencies]
error-chain = "0.12"
node-cli = { path = "cli" }
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }

[build-dependencies]
vergen = "2"

[patch.'https://github.com/paritytech/substrate']
substrate-trie = { path = "trie", default-features = false }

[workspace]
members = [
	"cli",
	"executor",
	"primitives",
	"runtime",
	"trie",
	"json",
	"util/keccak-hasher",
	"util/rlp",
]
exclude = [
	"runtime/wasm",
]

[profile.release]
panic = "unwind"
