[package]
name = "frontier-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Ethereum RPC (web3) compatibility layer for Substrate."
license = "GPL-3.0"

[dependencies]
jsonrpc-core = "14.0.3"
jsonrpc-derive = "14.0.3"
jsonrpc-core-client = "14.0.3"
ethereum-types = "0.9.0"
sp-api = { version = "2.0.0-dev", default-features = false, path = "../vendor/substrate/primitives/api" }
sp-runtime = { version = "2.0.0-dev", default-features = false, path = "../vendor/substrate/primitives/runtime" }
sp-blockchain = { version = "2.0.0-dev", default-features = false, path = "../vendor/substrate/primitives/blockchain" }
frontier-rpc-core = { path = "./core" }
frontier-rpc-primitives = { path = "./primitives" }
