[package]
name = "rlp"
version = "0.3.0"
description = "Recursive-length prefix encoding, decoding, and compression"
repository = "https://github.com/paritytech/parity-common"
license = "MIT/Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = { version = "1.0", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true }
rustc-hex = { version = "2.0", default-features = false, optional = true }

[dev-dependencies]
hex-literal = "0.1"

[features]
default = ["ethereum", "std"]
std = [
	"substrate-primitives/std",
	"byteorder/std",
	"rustc-hex",
	"rustc-hex/std",
]
ethereum = ["substrate-primitives"]
