[package]
name = "polkadot-validator"
version = "0.1.0"
authors = ["Parity Team <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
polkadot-primitives = { path = "../primitives", version = "0.1" }
polkadot-serializer = { path = "../serializer", version = "0.1" }
serde = "1.0"
