[package]
name = "runtime-polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
runtime-std = { path = "../std", version = "0.1" }

[features]
default = ["without-std"]
with-std = []
without-std = []
