[package]
name = "runtime-polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
polkadot-runtime-codec = { path = "../../runtime-codec", version = "0.1", default-features = false}
runtime-std = { path = "../std", version = "0.1" }

[features]
default = []
std = ["polkadot-runtime-codec/std"]
