[package]
name = "runtime-polkadot"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
runtime-support = { path = "../support", version = "0.1" }
