[package]
name = "polkadot-validator"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
substrate-primitives = { path = "../primitives" }
polkadot-primitives = { path = "../polkadot-primitives" }
substrate-serializer = { path = "../serializer" }
serde = "1.0"
