[package]
name = "substrate-test-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
hex-literal = { version = "0.1.0", optional = true }
substrate-codec = { path = "../../../substrate/codec", default-features = false }
substrate-runtime-std = { path = "../../../substrate/runtime-std", default-features = false }
substrate-runtime-io = { path = "../../../substrate/runtime-io", default-features = false }
substrate-runtime-support = { path = "../../../substrate/runtime-support", default-features = false }
substrate-primitives = { path = "../../../substrate/primitives", default-features = false }

[features]
default = []
std = [
	"hex-literal",
	"substrate-codec/std",
	"substrate-runtime-io/std",
	"substrate-runtime-std/std",
	"substrate-runtime-support/std",
	"substrate-primitives/std",
]

[profile.release]
panic = "abort"

[workspace]
members = []
