[package]
name = "polkadot-keystore"
version = "0.1.0"
authors = ["Parity Technologies <robert@parity.io>"]

[dependencies]
ethcore-crypto = { git = "https://github.com/paritytech/parity.git", default_features = false }
ed25519 = { path = "../../substrate/ed25519" }
error-chain = "0.11"
hex = "0.3"
rand = "0.4"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
subtle = "0.5"

[dev-dependencies]
tempdir = "0.3"
