[package]
name = "native-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[features]
default = ["with-std"]
with-std = []
without-std = []

[dependencies]
runtime-std = { path = "./std", version = "0.1" }
rustc-hex = "1.0"
