[package]
name = "polkadot-cli"
version = "0.1.0"
authors = ["Parity Team <admin@parity.io>"]
description = "Polkadot node implementation in Rust."

[dependencies]
clap = { version = "2.27", features = ["yaml"] }
env_logger = "0.4"
log = "0.3"
