[package]
name = "runtime-std"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[features]
strict = []

[dependencies]
lazy_static = "1.0.0"
parking_lot = "0.5"
polkadot-state-machine = { path = "../../state_machine" , version = "0.1" }
environmental = { path = "../../environmental", version = "0.1.0" }
polkadot-primitives = { path = "../../primitives", version = "0.1.0" }
triehash = "0.1.0"
