[package]
name = "basic_add"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which adds to a number as its state transition"

[lib]
crate-type = ["cdylib"]

[dependencies]
polkadot-parachain = { path = "../../", default-features = false }
wee_alloc = { git = "https://github.com/rustwasm/wee_alloc", rev = "4e9f23fff1f2474962085ca693f8884db666889f" }
tiny-keccak = "1.4"
pwasm-libc = "0.2"

[features]
default = ["std"]
std = ["polkadot-parachain/std"]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
