[package]
name = "polkadot-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
substrate-codec = { path = "../../substrate/codec", default_features = false }
substrate-primitives = { path = "../../substrate/primitives", default_features = false }
substrate-runtime-std = { path = "../../substrate/runtime-std", default_features = false }

[dev-dependencies]
substrate-serializer = { path = "../../substrate/serializer" }
pretty_assertions = "0.4"

[features]
default = ["std"]
std = [
	"substrate-codec/std",
	"substrate-primitives/std",
	"substrate-runtime-std/std",
	"serde_derive",
	"serde/std",
]
