[package]
name = "substrate-runtime-std"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]

[features]
default = ["std"]
std = []
nightly = []
strict = []
