[package]
name = "demo-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
substrate-codec = { path = "../../../substrate/codec", default-features = false }
substrate-runtime-std = { path = "../../../substrate/runtime-std", default-features = false }
substrate-runtime-io = { path = "../../../substrate/runtime-io", default-features = false }
substrate-runtime-support = { path = "../../../substrate/runtime-support", default-features = false }
substrate-primitives = { path = "../../../substrate/primitives", default-features = false }
demo-primitives = { path = "../../primitives", default-features = false }
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git", branch = "master" }

[features]
default = []
std = [
	"substrate-codec/std",
	"substrate-runtime-io/std",
	"substrate-runtime-std/std",
	"substrate-runtime-support/std",
	"substrate-primitives/std",
	"demo-primitives/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
