[package]
name = "runtime-std"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
pwasm-libc = { path = "../pwasm-libc", version = "0.1" }
pwasm-alloc = { path = "../pwasm-alloc", version = "0.1" }

[features]
strict = []
